{
 "title": "Virtual Machine Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_name", "label": "Datasource", "query": "influxdb" },
   {
    "name": "vm",
    "label": "Virtual Machine",
    "query": "SHOW TAG VALUES WITH KEY = \"vm_name\""
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "SHOW TAG VALUES From VirtualNetworkAdapter WITH KEY = \"interface_label\" WHERE vm_name =~ /$vm/ AND vm_name != ''"
   },
   {
    "name": "virtual_disk",
    "label": "Virtual Disk",
    "query": "SHOW TAG VALUES FROM VirtualDisk WITH KEY = \"disk_hardware_label\" WHERE vm_name =~ /$vm/"
   }
  ]
 },
 "panels": [
  { "title": "$virtual_disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "virtual_disk" },
  {
   "title": "Disk Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Disk Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "numberReadAveraged" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "Disk Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "numberWriteAveraged" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Bytes Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "alias": "Disk Bytes Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "Disk Bytes Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Disk Read Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "totalReadLatency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "Disk Write Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "totalWriteLatency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Seeks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Small Seeks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "smallSeeks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "Medium Seeks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "mediumSeeks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "Large Seeks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualDisk",
     "select": [
      [
       { "params": [ "largeSeeks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "disk_hardware_label", "operator": "=~", "value": "/^$virtual_disk$/" },
      { "condition": "AND", "key": "vm_name", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  { "title": "$interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }, "repeat": "interface" },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Received Bit/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "query": "SELECT mean(\"bytesRx\") *8192 FROM \"VirtualNetworkAdapter\" WHERE (\"guest_host_name\" =~ /^$vm$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "bytesRx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8192" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Transmitted Bit/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "select": [
      [
       { "params": [ "bytesTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8192" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "packetsRx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "select": [
      [
       { "params": [ "packetsRx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "broadcastRx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "query": "SELECT mean(\"broadcastRx\") FROM \"VirtualNetworkAdapter\" WHERE (\"guest_host_name\" =~ /^$vm$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "broadcastRx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "multicastRx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "query": "SELECT mean(\"multicastRx\") FROM \"VirtualNetworkAdapter\" WHERE (\"guest_host_name\" =~ /^$vm$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "multicastRx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "droppedRx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "query": "SELECT mean(\"droppedRx\") FROM \"VirtualNetworkAdapter\" WHERE (\"guest_host_name\" =~ /^$vm$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "droppedRx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "packetsTx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "select": [
      [
       { "params": [ "packetsTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "broadcastTx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "select": [
      [
       { "params": [ "broadcastTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "multicastTx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "select": [
      [
       { "params": [ "multicastTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "droppedTx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VirtualNetworkAdapter",
     "select": [
      [
       { "params": [ "droppedTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm$/" },
      { "condition": "AND", "key": "interface_label", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  }
 ]
}