ALTER TABLE compute_resource
  MODIFY COLUMN effective_cpu_mhz INT UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN effective_memory_size_mb BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN cpu_cores SMALLINT UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN cpu_threads SMALLINT UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN effective_hosts MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN hosts MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN total_memory_size_mb BIGINT(10) UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN total_cpu_mhz INT UNSIGNED NULL DEFAULT NULL;

INSERT INTO vspheredb_schema_migration
  (schema_version, migration_time)
  VALUES (57, NOW());
